### PR TITLE
GitHub has now deprecated the use of Node 16

### PR DESCRIPTION
**Pull request by brunchboy**
This change simply worked to solve the issue for my own action.

### CODE REVIEW

**Comment by brunchboy** [comment]
It looks like you need to update the actions your own build process uses. Many of those are also using node 16, and one is so old it is trying to use node 12, and so was forced to use node 16.

**Comment by Xotl** [comment]
Hi @brunchboy, good to see you around. I'll take a look at it as soon as I can.

**Comment by Xotl** [comment]
I will merge this PR into the branch of PR #23 (It also have other version updates) so it triggers the tests just to make sure it works fine.

**Comment by brunchboy** [comment]
Hi! I hope all is well with you, sorry I only seem to chat when there are GitHub deprecations to report. 😆 I was up until far too late on Friday night dealing with some incompatible changes in their version of PowerShell. And I realize now I should have mentioned beforehand that Chris and I spent a while enjoying Puerto Vallarta in December.

**Comment by Xotl** [comment]
Hi @brunchboy! no need to apologize, I really appreciate your PRs. 😃 

Ah, too bad to hear you've been struggling with incompatible stuff on Friday night. And Puerto Vallarta in December? That sounds like a delightful escape! Hope you had an amazing time there.

**Pull request merged**
